import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/Navbar";
import { Suspense } from "react";
import Loading from "./loading";
import TanStackProvider from "@/components/provider/tanstack-provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="px-5 py-3">
            <Navbar />
            <TanStackProvider>
              <Suspense fallback={<Loading />}>{children}</Suspense>
            </TanStackProvider>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
